version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  migrate:
    build: .
    command: npm run migrate
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - applogs:/app/logs
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES: ${JWT_EXPIRES}
    depends_on:
      - migrate
    networks:
      - app-network

volumes:
  pgdata:
  applogs:

networks:
  app-network:
    driver: bridge
