services:
  mongo:
    image: mongo:7.0
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PORT=8080
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
