name: backend-api-service-ci

on:
  push:
    branches: [main]
    paths:
      - "backend/api-service/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/api-service/**"
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # every Monday at 06:00 UTC

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/api-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build Project

    runs-on: ubuntu-latest

    needs: test

    defaults:
      run:
        working-directory: backend/api-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  deploy:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    env:

    defaults:
      run:
        working-directory: backend/api-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build migrate and app images
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          docker compose build migrate app

      - name: Push migrate and app images
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          docker compose push migrate app
