name: backend-ai-service-ci

on:
  push:
    branches: [main]
    paths:
      - "backend/ai-service/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/ai-service/**"
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # every Monday at 06:00 UTC

jobs:
  deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    defaults:
      run:
        working-directory: backend/ai-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ai-service-app:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ai-service-app:latest
